### PR TITLE
pin pip version to avoid version errors

### PR DESCRIPTION
**Pull request by jreynolds01**
Update to address future issues with pip package management issues

### CODE REVIEW

**Comment by jreynolds01** [comment]
blurgh, I did notice that, but didn't test before filing the PR. It was because I tried to do a really quick fix without running it (my kernel died, and I saved it anyway). I'll fix this and resubmit it - i was using AI ML Train test as my testing infra.

**Comment by jreynolds01** [comment]
pip itself is updated in conda at this point, so if this doesn't work, then we'll re run the build with the latest commit and see if there are still issues.

**Comment by jreynolds01** [comment]
ok, it failed. I'm bailing on this now, because now it's failing in a different, earlier step related azureml-sdk version issues. Let me build from scratch on the main branch and see if it is different...

**Comment by dciborow** [comment]
This PR needs to go into master, not "mabou/instrument'

Once the fix is in master, then we rebaes mabou/instrument on to master and commit the update.

**Comment by jreynolds01** [comment]
I'm going to close this PR - the instrument branch has diverged from master, the pip issue resolved itself with their new version. We should address in the future, but the bulk of the work is resolving hte difference between master and instrument.

**Pull request closed without merging**
